language: cpp
os: linux
dist: bionic
before_install:
  - sudo docker run --privileged linuxkit/binfmt:v0.6
  - sudo docker run --rm --privileged multiarch/qemu-user-static:register
services:
  - docker
compiler:
  - gcc
jobs:
  include:
  - name: "Pi stretch"
    env: DOCKERFILE=Dockerfile-pi-stretch
  - name: "Pi buster"
    env: DOCKERFILE=Dockerfile-pi-buster
script: docker build -f $DOCKERFILE --build-arg CLOUDSMITH_API_KEY=${CLOUDSMITH_API_KEY} .
